import Head from "next/head";
import React from "react";
import { GetServerSideProps, NextPage } from "next";
import CustomCard from "../components/common/CustomCard";
import AddNewRepositoryForm from "../components/Repositories/AddNewRepositoryForm";
import { IRepo } from "../models/Repository";
import { Card } from "react-bootstrap";
import moment from "moment";

const Home: NextPage<{
  repoList: IRepo[];
}> = (props) => {
  return (
    <>
      <Head>
        <title>Repo Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* {props.repoList.map((repo, index) => (
          <CustomCard key={index} url={`/${repo._id}`}>
            <Card.Title>{repo.repoName}</Card.Title>
            <Card.Text>
              <b>Created at: </b>
              {moment(repo.createdAt).format("LL")}
            </Card.Text>
          </CustomCard>
        ))} */}
      </div>
      <AddNewRepositoryForm />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const repoResponse = await fetch("http://localhost:3000/api/repositories");
    const repoList = await repoResponse.json();
    return {
      props: {
        repoList,
      },
    };
  } catch (error) {
    console.log(error);
  }
  return {
    props: {
      repoList: [],
    },
  };
};

export default Home;
